apiVersion: v1
kind: Service
metadata:
  name: player-service-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 9292
      nodePort: 30080          # Access the app locally at http://localhost:30080
  selector:
    app: player-service        # MUST match the label inside your deployment.yaml!